const jhean = new Object({
    nome: "Jhean",
    sobrenome: "Monteiro",
    idade: 21,
    falar: (nome=jhean.nome) => console.log(`${nome} está falando`),
    aumentaIdade: (idade=jhean.idade) => {return jhean.idade=(idade+1)},
    morreu: (nome=jhean.nome, sobrenome=jhean.sobrenome) => {console.log(nome+' '+sobrenome, "morreu, F no chat")}
})

jhean.falar()
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`))
console.log((`${jhean.nome} agora tem ${jhean.aumentaIdade()} anos de idade`)) 

jhean.morreu()